#!/usr/bin/env python3

import sys


if __name__ == "__main__":
    if "--cli" in sys.argv:
        from cli.cli import command_line_interface
        command_line_interface()
    else:
        from gtk3.application import Application
        app = Application()
        app.run(sys.argv)
