#!/usr/bin/env python3

import os, sys, configparser
import gettext

from utils.local_storage import get_local_data


if __name__ == "__main__":
    config_file = "config.ini"
    if not os.path.isfile(config_file):
        config_file = "config_default.ini"
    config = configparser.ConfigParser()
    try:
        config.read(config_file)
    except Exception as e:
        print("Error reading configuration data.")
        print(str(e))
        sys.exit()

    try:
        local_config = get_local_data(config=True)
    except Exception as e:
        print("Error reading configuration file.")
        print(str(e))
        sys.exit()

    lang = local_config.get('language', 'en')
    language = gettext.translation('base', localedir='po', languages=[lang])
    language.install()

    if "--cli" in sys.argv:
        from cli.cli import command_line_interface
        command_line_interface(config)
    else:
        from gtk3.application import Application
        app = Application(config=config)
        app.run(sys.argv)
