#!/usr/bin/env python3

import os
import sys
import configparser
import gettext

from komunitin_lite.core.local_storage import get_local_data


if __name__ == "__main__":
    config_file = "komunitin_lite/config.ini"
    if not os.path.isfile(config_file):
        config_file = "komunitin_lite/config_default.ini"
    config = configparser.ConfigParser()
    try:
        config.read(config_file)
    except Exception as e:
        print("Error reading configuration data.")
        print(str(e))
        sys.exit()

    try:
        local_config = get_local_data(config=True)
    except Exception as e:
        print("Error reading configuration file.")
        print(str(e))
        sys.exit()

    lang = local_config.get('language', 'en')
    language = gettext.translation('base', localedir='komunitin_lite/po',
                                   languages=[lang])
    language.install()

    if "--cli" in sys.argv:
        from komunitin_lite.cli.cli import CommandLineInterface
        cli = CommandLineInterface(config)
        cli.run()
    else:
        from komunitin_lite.gtk3.application import Application
        app = Application(config=config)
        app.run(sys.argv)
