#!/usr/bin/env python3

import os
import sys
import inspect
import configparser
import gettext

from komunitin_lite import get_base_path
from komunitin_lite.core.local_storage import get_local_data


if __name__ == "__main__":
    BASE_PATH = os.path.dirname(inspect.getfile(get_base_path))
    config_file = os.path.join(BASE_PATH, "config.ini")
    if not os.path.isfile(config_file):
        config_file = os.path.join(BASE_PATH, "config_default.ini")
    config = configparser.ConfigParser()
    try:
        config.read(config_file)
    except Exception as e:
        print("Error reading configuration data.")
        print(str(e))
        sys.exit()

    try:
        local_config = get_local_data(config=True)
    except Exception as e:
        print("Error reading configuration file.")
        print(str(e))
        sys.exit()

    lang = local_config.get('language', 'en')
    language = gettext.translation(
        'base', localedir=os.path.join(BASE_PATH, 'po'), languages=[lang])
    language.install()

    if "--cli" in sys.argv:
        from komunitin_lite.cli.cli import CommandLineInterface
        cli = CommandLineInterface(config)
        cli.run()
    else:
        from komunitin_lite.gtk3.application import Application
        app = Application(config=config, base_path=BASE_PATH)
        app.run(sys.argv)
